<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ticketflow-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketFlow.Booking.Api\TicketFlow.Booking.Api.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Api\TicketFlow.Events.Api.csproj" />
    <ProjectReference Include="..\TicketFlow.Notifications.Worker\TicketFlow.Notifications.Worker.csproj" />
    <ProjectReference Include="..\TicketFlow.Payments.Api\TicketFlow.Payments.Api.csproj" />
  </ItemGroup>

</Project>
