<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketFlow.BuildingBlocks\TicketFlow.BuildingBlocks.csproj" />
    <ProjectReference Include="..\TicketFlow.Contracts\TicketFlow.Contracts.csproj" />
    <ProjectReference Include="..\TicketFlow.ServiceDefaults\TicketFlow.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TicketFlow.Booking.UnitTests" />
  </ItemGroup>

</Project>
